config/routes.rb
Library::Application.routes.draw do
  
  resources :books do
    collection do
      get :search
    end
    resources :reservations, only: [:create, :new] do
      member do
        put :free
      end
    end
  end
  
  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  
  validates :title, presence: true, uniqueness: true
  validates :authors, presence: true
  
  validates_with IsbnValidator
  
  has_many :reservations
  
  def reservation
    self.reservations.where(state: 'reserved').first
  end
  
  def self.search_by_isbn(value)
    self.where(isbn: value)
  end

  def self.search_by_authors(value)
    self.where("authors LIKE ?", "%#{value}%").order(
               "authors asc, created_at desc")
  end

  def self.search_by_title(value)
    self.where("title LIKE ?", "%#{value}%").order(
         "title asc, created_at desc")
  end


  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  STATES = %w( free reserved )
  
  validates :book_id, presence: true
  validates :state,   inclusion: { in: STATES }
  validates :email,   presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  
  validates :book_id, uniqueness: { 
                        scope: :state, 
                        message: 'book has been already reserved' 
                   }, if: "state == 'reserved'"
                   
                   
  before_validation :make_reserved, :on => :create
  
  belongs_to :book
  
  def free
    self.update_attributes({state: 'free'})
  end
  
  
  private
  
  def make_reserved
    self.state = 'reserved'
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_filter :find_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
    respond_to do |format|
      format.html
      format.xml { render xml: @books.to_xml }
    end
  end
  
  def search
    @books = case params[:by]
      when 'isbn'    then Book.search_by_isbn(params[:query])
      when 'authors' then Book.search_by_authors(params[:query])
      else                Book.search_by_title(params[:query])
    end
    render action: :index
  end
  
  def show
    @book_reservation = @book.reservation
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(params[:book])
    if @book.save
      flash[:notice] = "Book created"
      redirect_to books_path
    else
      render action: :new
    end
  end
  
  def edit
  end
  
  def update
    if @book.update_attributes(params[:book])
      flash[:notice] = "Book saved"
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end
  
  def destroy
    @book.destroy
    flash[:notice] = "Book deleted"
    redirect_to books_path
  end
  
  
  private
  
  def find_book
    @book = Book.find(params[:id])
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  def new
    @book = Book.find(params[:book_id])
    @reservation = @book.reservations.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def create
    @book = Book.find(params[:book_id])
    @reservation = @book.reservations.new(params[:reservation])
    if @reservation.save
      flash[:notice] = "Book reserved"
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.js
      end
    else
      render :new
    end
  end
  
  def free
    @book = Book.find(params[:book_id])
    @reservation = @book.reservations.find(params[:id])
   
    if @reservation.free
      flash[:notice] = "Book is no longer reserved"
    else
      flash[:error]  = "Something went wrong"
    end
    redirect_to book_path(@book)
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(name)
    if name == :notice
      "alert alert-success"
    elsif name == :error
      "alert alert-error"
    else
      "alert"
    end
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
  
  def query_by_radio_tag(field)
    checked = params[:by].blank? ? 
                    field.to_s == 'title' : params[:by] == field.to_s
    output = ""
    output << (radio_button_tag :by, field, checked)
    output << field.to_s.titleize
    content_tag(:span, raw(output))
  end
  
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { class: 'form-horizontal' } do |f| %>
  
  <% unless @book.errors.empty? %>
    <div class='alert alert-block alert-error'>
      <h2 class='alert-heading'>Failed to save book</h2>
      <% @book.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <fieldset>
    <div class='control-group'>
      <label class='control-label' for="title">Title</label>
      <div class='controls'>
        <%= f.text_field :title %>
      </div>
  </fieldset>
  
  <fieldset>
    <div class='control-group'>
      <label class='control-label' for="authors">Authors</label>
      <div class='controls'>
        <%= f.text_field :authors %>
      </div>
  </fieldset>
  
  <fieldset>
    <div class='control-group'>
      <label class='control-label' for="isbn">ISBN</label>
      <div class='controls'>
        <%= f.text_field :isbn %>
      </div>
  </fieldset>

  <fieldset>
    <div class='control-group'>
      <label class='control-label' for="description">Description</label>
      <div class='controls'>
        <%= f.text_field :description %>
      </div>
  </fieldset>

  <fieldset>
    <div class='controls'>
      <%= f.submit "Save", class: 'btn-primary' %>
      or
      <%= link_to "Cancel", books_path %>
    </div>
  </fieldset>
  
  
<% end %>

app/views/books/_reservation_links.html.erb
<% if reservation %>
  <%= link_to "Free", free_book_reservation_path(book, reservation), method: :put, class: 'btn' %>
<% else %>
  <%= link_to "Reserve", new_book_reservation_path(book), class: 'btn', remote: true %>
<% end %>

app/views/books/_reservation_status.html.erb
<% if reservation %>
  <span class="label important">Reserved by <%= reservation.email %></span>
<% else %>
  <span class="label success">Free</span>
<% end %>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title%></h1>

<%= render partial: 'form' %>

app/views/books/index.html.erb
<%= form_tag search_books_path, method: :get do %>
  <%= text_field_tag :query, params[:query] || 'Search by title' %>
  <%= submit_tag 'Search', class: 'btn-primary' %>
  <div>
    <%= query_by_radio_tag :title %>
    <%= query_by_radio_tag :isbn %>
    <%= query_by_radio_tag :authors %>
  </div>
<% end %>

<p>
  <%= link_to "Add a book", new_book_path, class: 'btn' %>
</p>

<% if @books.size > 0 %>
  <dl>
  <% @books.each do |book| %>
    <dt><%= link_to book.title, book_path(book) %></dt>
    <dd><%= book.authors %></dd>
  <% end %>
  </dl>
<% else %>
  <h2>Sorry, we haven't found any books!</h2>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render partial: 'form' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<div id="reservation-status">
  <%= render partial: "reservation_status", locals: {reservation: @book_reservation} %>
</div>

<p>
	by <%= @book.authors %>
</p>

<p>
	ISBN: <%= @book.isbn %>
</p>

<p>
	<%= @book.description %>
</p>

<%= link_to "Edit", edit_book_path(@book), class: 'btn' %>

<span id="reservation-links">
  <%= render partial: "reservation_links", locals: {book: @book, reservation: @book_reservation} %>
</span>

<%= link_to "Delete", book_path, method: :delete, class: 'btn btn-danger' %>

<p>
  <%= link_to "Back to list", books_path %>
</p>


<div id="reservation-form" style="display: none;">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container main">
    
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to root_path, class: 'brand' do %>
            <%= image_tag "books.png", width: '20px' %>  
            Library
          <% end %>
        </div>
      </div>
    </div>
  
    <% flash.each do |name,msg| %>
      <div class="<%= flash_class(name)%>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  
  </div>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for [@book, @reservation], remote: remote do |f| %>

  <% unless @reservation.errors.empty? %>
    <h2>Failed create reservation book</h2>
    <% @reservation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>

  <div>
    Email:<br/>
    <%= f.text_field :email %>
  </div>

  <%= f.submit "Save" %>
  or
  <%= link_to "Cancel", book_path(@book) %>

<% end %>

app/views/reservations/_new.html.erb
<h3>Reserve</h3>

<%= render partial: 'form', locals: { remote: true } %>

app/views/reservations/create.js.erb
$('#reservation-form').hide();
$('#reservation-status').html("<%=j render partial: "books/reservation_status", locals: {reservation: @reservation} %>");
$('#reservation-links').html('<%=j render partial: "books/reservation_links", locals: {book: @book, reservation: @reservation} %>');

app/views/reservations/new.html.erb
<h1>New reservation for "<%= @book.title %>"</h1>

<%= render partial: 'form', locals: { remote: true } %>

app/views/reservations/new.js.erb
$('#reservation-form').html("<%=j render "new" %>").show();

app/views/site/index.html.erb
<h1>Book Library</h1>
<p>
  Welcome to our library!
</p>
<p>
  We will open in 5 weeks.
</p>